import { createClientStore } from './data/Store.js';
import { PeerId } from '@automerge/automerge-repo';
const result = await createClientStore(['127.0.0.1'], 'string-test' as PeerId, '4GQmEZehPDfryGDxkFo9XixbvmAC' as any, 10);
const doc = result.handle.doc() as any;
const user = Object.values(doc.userDB)[0] as any;
const raw = user.passwordHash;
const asString = String(raw);
console.log('typeof raw:', typeof raw);
console.log('raw.constructor.name:', raw?.constructor?.name);
console.log('String() length:', asString.length);
console.log('String() value:', asString);
console.log('=== same as stored? ===', asString === '$2b$12$oGvtS39MsflSyC.UpsLZ3uhIMm55lbGzXxkE/xUxwNmhg2y6E0rvG');
result.repo.shutdown();
process.exit(0);
